export const Roles = {
  ADMIN: "ADMIN",
  MANAGER: "manager",
  MECHANIC: "mechanic",
  TECHNICIAN: "technician",
  MANAGING_DIRECTOR: "managing_director",
  CEO: "ceo",
  ACCOUNTANT: "accountant",
  SALES: "sales",
  DRIVER: "driver",
  CLEANER: "cleaner",
  SECURITY: "security",
  DISPATCHER: "dispatcher",
  SUPERVISOR: "supervisor",
  IT: "it",
  HR: "hr",
  RECEPTIONIST: "receptionist",
  CUSTOMER_SERVICE: "customer_service",
  
};
